<a href="https://colab.research.google.com/github/FarelTech/metode-numerik/blob/main/Implementasi%20Persamaan%20Sistem%20Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Mendefinisikan matriks
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Menghitung matriks balikan
try:
    A_inv = np.linalg.inv(A)
    print("Matriks asli:")
    print(A)
    print("Matriks balikan:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("Matriks tidak dapat dibalik (determinannya nol).")

# Verifikasi dengan mengalikan matriks asli dengan balikan
# Harus menghasilkan matriks identitas
identity_check = np.dot(A, A_inv)
print("Hasil perkalian matriks asli dengan balikan (harus matriks identitas):")
print(identity_check)

Matriks asli:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Matriks balikan:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
Hasil perkalian matriks asli dengan balikan (harus matriks identitas):
[[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]


In [ ]:
import numpy as np

def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # U bagian atas
        for k in range(i, n):
            sum_u = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - sum_u

        # L bagian bawah
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal L adalah 1
            else:
                sum_l = sum(L[k][j] * U[j][i] for j in range(i))
                L[k][i] = (A[k][i] - sum_l) / U[i][i]

    return L, U

# Contoh penggunaan
A = np.array([[2, -1, -2],
              [-4, 6, 3],
              [-4, -2, 8]], dtype=float)

L, U = lu_decomposition(A)

print("Matriks A:")
print(A)
print("Matriks L:")
print(L)
print("Matriks U:")
print(U)

# Verifikasi bahwa A = L * U
A_reconstructed = np.dot(L, U)
print("Rekonstruksi A dari L dan U (harus sama dengan matriks A asli):")
print(A_reconstructed)

Matriks A:
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]
Matriks L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]
Matriks U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]
Rekonstruksi A dari L dan U (harus sama dengan matriks A asli):
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]


In [ ]:
def crout_decomposition(A):
    n = len(A)
    L = [[0.0] * n for _ in range(n)]
    U = [[0.0] * n for _ in range(n)]

    for j in range(n):
        for i in range(j, n):
            sum_l = sum(L[i][k] * U[k][j] for k in range(j))
            L[i][j] = A[i][j] - sum_l

        U[j][j] = 1  # Diagonal U harus 1
        for i in range(j + 1, n):
            sum_u = sum(L[j][k] * U[k][i] for k in range(j))
            U[j][i] = (A[j][i] - sum_u) / L[j][j]

    return L, U

# Contoh penggunaan
A = [[2, -1, -2],
     [-4, 6, 3],
     [-4, -2, 8]]

L, U = crout_decomposition(A)

print("Matriks A:")
for row in A:
    print(row)
print("Matriks L:")
for row in L:
    print(row)
print("Matriks U:")
for row in U:
    print(row)

# Verifikasi bahwa A = L * U
def matrix_multiply(X, Y):
    result = [[0] * len(Y[0]) for _ in range(len(X))]
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(Y)):
                result[i][j] += X[i][k] * Y[k][j]
    return result

A_reconstructed = matrix_multiply(L, U)
print("Rekonstruksi A dari L dan U (harus sama dengan matriks A asli):")
for row in A_reconstructed:
    print(row)

Matriks A:
[2, -1, -2]
[-4, 6, 3]
[-4, -2, 8]
Matriks L:
[2, 0.0, 0.0]
[-4, 4.0, 0.0]
[-4, -4.0, 3.0]
Matriks U:
[1, -0.5, -1.0]
[0.0, 1, -0.25]
[0.0, 0.0, 1]
Rekonstruksi A dari L dan U (harus sama dengan matriks A asli):
[2.0, -1.0, -2.0]
[-4.0, 6.0, 3.0]
[-4.0, -2.0, 8.0]
